docker exec tf-container \
    python main.py \
    --phase 'train' \
    --dataset 'cat_final1' \
    --epoch 100 \
    --iteration 10000 \
    --batch_size 1 \
    --print_freq 1000 \
    --save_freq 10000 \
    --decay_flag True \
    --decay_epoch 50 \
    --lr 0.0001 \
    --GP_ld 10 \
    --adv_weight 1 \
    --cycle_weight 10 \
    --identity_weight 10 \
    --cam_weight 1000 \
    --gan_type 'lsgan' \
     --smoothing True \
    --ch 16 \
    --n_res 4 \
    --n_dis 6 \
    --n_critic 1 \
    --sn True \
    --img_size 256 \
    --img_ch 3 \
    --augment_flag True \
    --checkpoint_dir home\tmp\checkpoint
